#设置服务器端口
server: 
  port: 8888

spring: 
  #配置数据库
  datasource: 
    url: jdbc:mysql://localhost:3306/testdb?charsetEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  #检查mybatis配置文件是否存在
  check-config-location: true
  #mybatis配置文件的位置
  config-location: classpath:mybatis/mybatis-config.xml
  #mapper文件的位置
  mapper-locations: classpath*:mapper/*Mapper.xml

#打印日志
logging: 
  level:
    com.java.mapper: debug